import React from 'react';
import Navbar from '../components/Navbar/Navbar';
import { ShieldCheck, Cpu, Database, Server, CheckCircle2, Lock, Terminal, Sparkles } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, Badge } from '../components/ui';

export default function Settings() {
  return (
    <div className="min-h-screen bg-background text-text-primary flex flex-col font-sans selection:bg-primary/30 selection:text-primary relative">
      <Navbar isConnected={true} activeDataset={null} />

      <main role="main" className="flex-1 max-w-4xl w-full mx-auto p-6 md:p-8 space-y-6 relative z-10">
        <div className="relative animate-fade-in-up">
          <h1 className="text-2xl md:text-3xl font-extrabold text-text-primary tracking-tight font-display">
            System Settings & Security
          </h1>
          <p className="text-sm text-text-secondary mt-1">
            System configuration, sandboxed execution rules, model parameters, and database state.
          </p>
        </div>

        {/* Section 1: LLM & Inference Engine */}
        <section aria-labelledby="inference-heading" className="card-elevated space-y-4 relative overflow-hidden animate-fade-in-up" style={{ transitionDelay: '100ms' }}>
          <div className="flex items-center space-x-2 text-text-primary font-bold text-base md:text-lg">
            <div className="w-8 h-8 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center text-primary">
              <Cpu className="w-4 h-4" aria-hidden="true" />
            </div>
            <h2 id="inference-heading">LLM & Inference Configuration</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs md:text-sm">
            <Card variant="bordered" padding="md">
              <span className="text-text-muted text-xs font-semibold uppercase tracking-wider">Active Model</span>
              <div className="font-bold text-text-primary mt-1 text-sm md:text-base font-mono-tight">llama-3.3-70b-versatile</div>
              <Badge variant="primary" className="mt-2.5 inline-block">
                Groq API Hardware Acceleration
              </Badge>
            </Card>

            <Card variant="bordered" padding="md">
              <span className="text-text-muted text-xs font-semibold uppercase tracking-wider">Execution Mode</span>
              <div className="font-bold text-text-primary mt-1 text-sm md:text-base">Structured JSON Code Generation</div>
              <Badge variant="primary" className="mt-2.5 inline-block">
                Anti-Hallucination 2-Pass Pipeline
              </Badge>
            </Card>
          </div>
        </section>

        {/* Section 2: AST Execution Sandbox Safety */}
        <section aria-labelledby="sandbox-heading" className="card-elevated space-y-4 relative overflow-hidden animate-fade-in-up" style={{ transitionDelay: '200ms' }}>
          <div className="flex items-center space-x-2 text-text-primary font-bold text-base md:text-lg">
            <div className="w-8 h-8 rounded-lg bg-success/10 border border-success/20 flex items-center justify-center text-success">
              <ShieldCheck className="w-4 h-4" aria-hidden="true" />
            </div>
            <h2 id="sandbox-heading">AST Security & Execution Sandbox</h2>
          </div>

          <p className="text-xs md:text-sm text-text-secondary leading-relaxed">
            All code generated by the LLM is statically validated via Python AST before execution in a restricted namespace.
          </p>

          <div className="space-y-2.5 text-xs md:text-sm">
            <div className="flex items-center justify-between card p-3.5 rounded-xl">
              <span className="font-medium text-text-primary">Import Statements Blocked</span>
              <Badge variant="success">
                Enforced (ast.Import, ast.ImportFrom)
              </Badge>
            </div>

            <div className="flex items-center justify-between card p-3.5 rounded-xl">
              <span className="font-medium text-text-primary">Blocked System Calls</span>
              <Badge variant="success" className="font-mono-tight text-[10px]">
                eval, exec, open, compile, __import__
              </Badge>
            </div>

            <div className="flex items-center justify-between card p-3.5 rounded-xl">
              <span className="font-medium text-text-primary">Execution Watchdog Timeout</span>
              <Badge variant="primary" className="font-mono-tight">
                10 Seconds Thread Limit
              </Badge>
            </div>

            <div className="flex items-center justify-between card p-3.5 rounded-xl">
              <span className="font-medium text-text-primary">Result Memory Cap</span>
              <Badge variant="primary" className="font-mono-tight">
                Max 1,000 Rows Returned
              </Badge>
            </div>
          </div>
        </section>

        {/* Section 3: SQLite Database & Logs */}
        <section aria-labelledby="database-heading" className="card-elevated space-y-4 relative overflow-hidden animate-fade-in-up" style={{ transitionDelay: '300ms' }}>
          <div className="flex items-center space-x-2 text-text-primary font-bold text-base md:text-lg">
            <div className="w-8 h-8 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center text-primary">
              <Database className="w-4 h-4" aria-hidden="true" />
            </div>
            <h2 id="database-heading">Database Persistence & Logging</h2>
          </div>

          <Card variant="bordered" padding="md">
            <div className="space-y-2 text-xs md:text-sm">
              <div className="flex justify-between flex-wrap gap-1">
                <span className="text-text-muted font-medium">Database System:</span>
                <span className="font-mono-tight text-text-primary font-semibold">PostgreSQL / Neon & SQLite</span>
              </div>
              <div className="flex justify-between flex-wrap gap-1">
                <span className="text-text-muted font-medium">Table Schema:</span>
                <span className="font-mono-tight text-text-secondary">users, logs (id, timestamp, dataset_name, ...)</span>
              </div>
            </div>
          </Card>
        </section>
        
        {/* Section 4: Visual Settings */}
        <section aria-labelledby="visual-heading" className="card-elevated space-y-4 relative overflow-hidden animate-fade-in-up" style={{ transitionDelay: '400ms' }}>
          <div className="flex items-center space-x-2 text-text-primary font-bold text-base md:text-lg">
            <div className="w-8 h-8 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center text-primary">
              <Sparkles className="w-4 h-4" aria-hidden="true" />
            </div>
            <h2 id="visual-heading">Visual Environment</h2>
          </div>

          <p className="text-xs md:text-sm text-text-secondary leading-relaxed">
            The interactive workflow visualization runs on the landing page. Adjust visual preferences below.
          </p>

          <div className="space-y-3">
            <label className="flex items-center justify-between cursor-pointer">
              <span className="font-medium text-text-primary text-sm">Reduced Motion</span>
              <input
                type="checkbox"
                className="w-10 h-5 rounded-full bg-surface-secondary border border-border appearance-none relative after:content-[''] after:absolute after:top-0.5 after:left-0.5 after:w-4 after:h-4 after:bg-white after:rounded-full after:transition-all checked:after:left-5 checked:bg-primary checked:border-primary focus:outline-none focus:ring-2 focus:ring-primary"
              />
            </label>
            <label className="flex items-center justify-between cursor-pointer">
              <span className="font-medium text-text-primary text-sm">Ambient Animations</span>
              <input
                type="checkbox"
                defaultChecked
                className="w-10 h-5 rounded-full bg-surface-secondary border border-border appearance-none relative after:content-[''] after:absolute after:top-0.5 after:left-0.5 after:w-4 after:h-4 after:bg-white after:rounded-full after:transition-all checked:after:left-5 checked:bg-primary checked:border-primary focus:outline-none focus:ring-2 focus:ring-primary"
              />
            </label>
            <label className="flex items-center justify-between cursor-pointer">
              <span className="font-medium text-text-primary text-sm">Interactive Workflow</span>
              <input
                type="checkbox"
                defaultChecked
                className="w-10 h-5 rounded-full bg-surface-secondary border border-border appearance-none relative after:content-[''] after:absolute after:top-0.5 after:left-0.5 after:w-4 after:h-4 after:bg-white after:rounded-full after:transition-all checked:after:left-5 checked:bg-primary checked:border-primary focus:outline-none focus:ring-2 focus:ring-primary"
              />
            </label>
          </div>
        </section>
      </main>
    </div>
  );
}