import React from 'react';
import Navbar from '../components/Navbar/Navbar';
import { ShieldCheck, Cpu, Database } from 'lucide-react';

export default function Settings() {
  return (
    <div className="min-h-screen bg-[#F8FAFC] flex flex-col font-sans">
      <Navbar isConnected={true} />

      <main role="main" className="flex-1 max-w-4xl w-full mx-auto p-6 md:p-8 space-y-6">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold text-gray-900 tracking-tight">
            System Settings & Security
          </h1>
          <p className="text-sm md:text-base text-gray-600 mt-1">
            System configuration, sandboxed execution rules, model parameters, and database state.
          </p>
        </div>

        {/* Section 1: LLM & Inference Engine */}
        <section aria-labelledby="inference-heading" className="bg-white border border-gray-200 rounded-lg p-6 shadow-sm space-y-4">
          <div className="flex items-center space-x-2 text-gray-900 font-bold text-base md:text-lg">
            <Cpu className="w-5 h-5 text-blue-500" aria-hidden="true" />
            <h2 id="inference-heading">LLM & Inference Configuration</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs md:text-sm">
            <div className="bg-slate-50 border border-slate-200 rounded-md p-4">
              <span className="text-gray-500 text-xs font-semibold uppercase tracking-wider">Active Model</span>
              <div className="font-bold text-gray-900 mt-1 text-sm md:text-base">llama-3.3-70b-versatile</div>
              <span className="text-xs text-emerald-700 bg-emerald-50 border border-emerald-200 px-2.5 py-0.5 rounded-full font-semibold mt-2.5 inline-block">
                Groq API Hardware Acceleration
              </span>
            </div>

            <div className="bg-slate-50 border border-slate-200 rounded-md p-4">
              <span className="text-gray-500 text-xs font-semibold uppercase tracking-wider">Execution Mode</span>
              <div className="font-bold text-gray-900 mt-1 text-sm md:text-base">Structured JSON Code Generation</div>
              <span className="text-xs text-blue-700 bg-blue-50 border border-blue-200 px-2.5 py-0.5 rounded-full font-semibold mt-2.5 inline-block">
                Anti-Hallucination 2-Pass Pipeline
              </span>
            </div>
          </div>
        </section>

        {/* Section 2: AST Execution Sandbox Safety */}
        <section aria-labelledby="sandbox-heading" className="bg-white border border-gray-200 rounded-lg p-6 shadow-sm space-y-4">
          <div className="flex items-center space-x-2 text-gray-900 font-bold text-base md:text-lg">
            <ShieldCheck className="w-5 h-5 text-emerald-600" aria-hidden="true" />
            <h2 id="sandbox-heading">AST Security & Execution Sandbox</h2>
          </div>

          <p className="text-xs md:text-sm text-gray-600 leading-relaxed">
            All code generated by the LLM is statically validated via Python AST before execution in a restricted namespace.
          </p>

          <div className="space-y-2.5 text-xs md:text-sm">
            <div className="flex items-center justify-between bg-slate-50 p-3.5 rounded-md border border-slate-200">
              <span className="font-medium text-slate-800">Import Statements Blocked</span>
              <span className="text-emerald-700 font-semibold bg-emerald-100 px-2.5 py-0.5 rounded text-xs">
                Enforced (ast.Import, ast.ImportFrom)
              </span>
            </div>

            <div className="flex items-center justify-between bg-slate-50 p-3.5 rounded-md border border-slate-200">
              <span className="font-medium text-slate-800">Blocked System Calls</span>
              <span className="text-emerald-700 font-semibold bg-emerald-100 px-2.5 py-0.5 rounded text-xs">
                eval, exec, open, compile, __import__
              </span>
            </div>

            <div className="flex items-center justify-between bg-slate-50 p-3.5 rounded-md border border-slate-200">
              <span className="font-medium text-slate-800">Execution Watchdog Timeout</span>
              <span className="text-blue-700 font-semibold bg-blue-100 px-2.5 py-0.5 rounded text-xs">
                10 Seconds Thread Limit
              </span>
            </div>

            <div className="flex items-center justify-between bg-slate-50 p-3.5 rounded-md border border-slate-200">
              <span className="font-medium text-slate-800">Result Memory Cap</span>
              <span className="text-blue-700 font-semibold bg-blue-100 px-2.5 py-0.5 rounded text-xs">
                Max 1,000 Rows Returned
              </span>
            </div>
          </div>
        </section>

        {/* Section 3: SQLite Database & Logs */}
        <section aria-labelledby="database-heading" className="bg-white border border-gray-200 rounded-lg p-6 shadow-sm space-y-4">
          <div className="flex items-center space-x-2 text-gray-900 font-bold text-base md:text-lg">
            <Database className="w-5 h-5 text-purple-600" aria-hidden="true" />
            <h2 id="database-heading">SQLite Persistence & Logging</h2>
          </div>

          <div className="bg-slate-50 p-4 rounded-md border border-slate-200 text-xs md:text-sm space-y-2.5">
            <div className="flex justify-between flex-wrap gap-1">
              <span className="text-gray-500 font-medium">Database Path:</span>
              <span className="font-mono text-gray-800 font-semibold">logs/agent_logs.db</span>
            </div>
            <div className="flex justify-between flex-wrap gap-1">
              <span className="text-gray-500 font-medium">Table Schema:</span>
              <span className="font-mono text-gray-800">logs (id, timestamp, dataset_name, question, ...)</span>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

